name: Manual Release

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch
        - auto
      create-release-branch:
        description: 'Create release branch'
        required: false
        default: false
        type: boolean

jobs:
  release:
    uses: treasurenetprotocol/reusable-workflows/.github/workflows/reusable-semantic-release.yml@main
    with:
      working-directory: '.'
      release-branch: ${{ github.ref_name }}
      tag-prefix: 'v'
      auto-create-release-branch: ${{ inputs.create-release-branch }}
      bump-type: ${{ inputs.bump-type }}
    permissions:
      contents: write
      pull-requests: write